Project restaurant {
  database_type: 'PostgreSQL'
}

/*****************************************************************************************
*                                        Catalogs                                        *
*****************************************************************************************/

// Status
Table restaurant.status {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    description varchar(64) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

// Wharehouse status
Table restaurant.wharehouse_status {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    description varchar(64) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

// Areas status
Table restaurant.areas_status {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    description varchar(64) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

// Shopping list status
Table restaurant.shopping_list_status {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    description varchar(64) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

// Recipes status
Table restaurant.recipes_status {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    description varchar(64) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

// Countries
Table restaurant.countries {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    clave varchar(2) [not null, Note: 'ISO 3166-1 alpha-2 code']
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

// Meassurment units
Table restaurant.measurement_units {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    description varchar(128) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

// Fiscal regimes
Table restaurant.fiscal_regimes {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    description varchar(128) [not null]
    clave varchar(2) [not null, Note: 'SAT fiscal regime code']
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

// Flow types
Table restaurant.flow_types {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    description varchar(64) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]

    Note: 'Flow types as cost or outcome'
}

/**
* Movement types
* Son los tipos de movimientos que se pueden hacer en los almacenes, estos pueden ser del
* tipo:
*   - Entrada
*   - Salida
*   - Traslado
*   - Ajuste
*   - Merma
*/
Table restaurant.movement_types {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(94) [not null]
    description varchar(128) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

/*****************************************************************************************
*                                        Restaurant                                      *
*****************************************************************************************/

/**
*  Warehouse
*  Es el almacen del grupo restaurantero donde se pondrán los espacios para los registros
*  de los productos que se manejarán en el restaurante, de esta manera se puede llevar un 
*  registro de los movimientos así como poder transladar cantidades entre restaurantes o
*  areas.
*/
Table restaurant.warehouses {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(128) [not null]

    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    status_id int [ref: > restaurant.wharehouse_status.id]
    address_id UUID [ref: > restaurant.addresses.id]
}

/**
* Wharehouse Slots
* Son los espacios en los que se van a sumar o restar la cantidad de productos que se tienen
* sin importar la variante o proveedor que se haya adquirido.
*/
Table restaurant.warehouse_slots {
    id UUID [pk, default: `uuid_generate_v4()`]
    product_name varchar(128) [not null]
    yield decimal(12,6) [not null] // rendimiento que se le asigna al producto
    product_id UUID [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    measurement_unit_id int [ref: > restaurant.measurement_units.id]
    warehouse_id UUID [ref: > restaurant.warehouses.id]
    area_id UUID [ref: > restaurant.areas.id]
    flow_types_id int [ref: > restaurant.flow_types.id]
}

/**
* Slot_movements
* Son los registros que se van dejando en los espacios de los almacenes para llevar un
* historial
*/
Table restaurant.slot_movements {
    id UUID [pk, default: `uuid_generate_v4()`]
    bill_name varchar(128) [not null]
    variant_id UUID [not null]
    product_id UUID [not null]

    quantity decimal(12,6) [not null]
    cost decimal(12,6) [not null]

    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    warehouse_slot_id UUID [ref: > restaurant.warehouse_slots.id]
    movement_type_id int [ref: > restaurant.movement_types.id]
}
Ref: restaurant.slot_movements.id > restaurant.orders.id

// Restaurant information
Table restaurant.restaurants {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(128) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    status_id int [ref: > restaurant.status.id]
    warehouse_id UUID [ref: > restaurant.warehouses.id]
    delivery_address_id UUID [ref: > restaurant.addresses.id]
    country_id UUID [ref: > restaurant.countries.id]
}

// Restaurant Areas
Table restaurant.areas {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(64) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    status_id int [ref: > restaurant.areas_status.id]
    restaurant_id UUID [ref: > restaurant.restaurants.id]
}

// Restaurant Menu sections
Table restaurant.menu_sections {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(64) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    restaurant_id UUID [not null, ref: > restaurant.restaurants.id]
}

// Restaurant shopping list
Table restaurant.shopping_lists {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(64) [not null]
    description varchar(128) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    status_id int [ref: > restaurant.shopping_list_status.id]
    restaurant_id UUID [ref: > restaurant.restaurants.id]
}

// Restaurant shopping list items
Table restaurant.shopping_list_items {
    id UUID [pk, default: `uuid_generate_v4()`]
    quantity decimal(12,6) [not null]
    product_id UUID [not null]
    variant_id UUID [null, Note: 'Can be null to avoid variant dependency']

    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    shopping_list_id UUID [ref: > restaurant.shopping_lists.id]

    area_id UUID [ref: > restaurant.areas.id]
}

// Orders
Table restaurant.orders {
    id UUID [pk, Note: 'Generated by consuming Marketplace API']
    identifier varchar(8) [not null,Note: 'Template: YYMMXXXX']
    provider_id UUID [not null]

    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    area UUID [ref: > restaurant.areas.id]
    // indexes
    uuid_index varchar(8) [unique]
}

// Order items
Table restaurant.order_items {
    id UUID [pk, default: `uuid_generate_v4()`]
    quantity decimal(12,6) [not null]
    cost decimal(12,6) [not null]
    product_id UUID [not null]
    variant_id UUID [not null]
    bill_name varchar(128) [not null]
    description varchar(128) [not null]
    brand varchar(128) [not null]
    content varchar(128) [not null]

    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    order_id UUID [ref: > restaurant.orders.id]
    measurement_unit_id int [ref: > restaurant.measurement_units.id]
}

// General address table
Table restaurant.addresses {
    id UUID [pk, default: `uuid_generate_v4()`]
    street varchar(128) [not null]
    exterior varchar(64) [not null]
    interior varchar(64) [not null]
    neighborhood varchar(128) [not null]
    city varchar(128) [not null]
    state varchar(128) [not null]
    zip varchar(32) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
}

// Recipes
Table restaurant.recipes {
    id UUID [pk, default: `uuid_generate_v4()`]
    // Falta la relación con el usuario
    created_by UUID [not null]

    name varchar(128) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    status_id int [ref: > restaurant.recipes_status.id]
    area_id UUID [ref: > restaurant.areas.id]
    section_id UUID [ref: > restaurant.menu_sections.id]
    restaurant_id UUID [ref: > restaurant.restaurants.id]
}

// Recipe items
Table restaurant.recipe_items {
    id UUID [pk, default: `uuid_generate_v4()`]
    quantity decimal(12,6) [not null]
    name varchar(128) [not null]
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    subrecipe_id UUID [ref: > restaurant.subrecipes.id] // Un item puede ser una subreceta
    product_id UUID [ref: > restaurant.products.id] // Un item puede ser un producto
    recipe_id UUID [nut null, ref: > restaurant.recipes.id]
    measurement_unit_id int [nut null, ref: > restaurant.measurement_units.id]
}

// Subrecipes
Table restaurant.subrecipes {
    id UUID [pk, default: `uuid_generate_v4()`]
    yield decimal(12,6) [not null]
    // relations
    meassurment_unit_id int [ref: > restaurant.measurement_units.id]
    recipe_id UUID [ref: > restaurant.recipes.id]
}

/*****************************************************************************************
*                                          Taxes                                         *
*****************************************************************************************/

// Tax information
Table restaurant.tax_informations {
    id UUID [pk, default: `uuid_generate_v4()`]
    name varchar(255) [not null]
    rfc varchar(13) [not null, Note: 'RFC']
    
    // Consultar las opcions de seguridad
    // Revisar si es necesrio para Restaurantes
    private_key_pass varchar(255) [not null]
    
    created_at timetz [default: `now()`]
    updated_at timetz [default: `now()`]
    deleted_at timetz [null]
    active bool [default: true]
    // relations
    fiscal_regime_id int [ref: > restaurant.fiscal_regimes.id]

    Note: 'Tax information'
}
Ref: restaurant.tax_informations.id <> restaurant.restaurants.id
